/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docsSidebar: [
    'intro',
    'platform-overview',
    {
      type: 'category',
      label: 'User Guides',
      items: [
        'user-guides/index',
        'user-guides/getting-started',
        'user-guides/account-management',
      ],
    },
    {
      type: 'category',
      label: 'Core Features',
      items: [
        'features/peer-support-groups',
        'features/professional-therapy',
        'features/ai-mental-health-bots',
        'features/tokenized-incentives',
        'features/decentralized-anonymity',
      ],
    },
    {
      type: 'category',
      label: 'Mentorship Programs',
      items: [
        'mentorship/index',
        'mentorship/peer-mentorship',
        'mentorship/professional-mentorship',
        'mentorship/specialized-mentorship',
      ],
    },
    {
      type: 'category',
      label: 'Web3 Technology',
      items: [
        'web3-technology/index',
        'web3-technology/internet-computer',
        'web3-technology/smart-contracts',
        'web3-technology/tokenomics',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: [
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/deploy-your-site',
    //     'tutorial-basics/congratulations',
    //   ],
    // },
  ],

  apiSidebar: [
    'api/introduction',
    {
      type: 'category',
      label: 'Authentication',
      items: [
        'api/auth/overview',
        'api/auth/wallet-connection',
        'api/auth/session-management',
      ],
    },
    {
      type: 'category',
      label: 'Users',
      items: [
        'api/users/profile-management',
      ],
    },
    {
      type: 'category',
      label: 'Therapy',
      items: [
        'api/therapy/booking',
      ],
    },
    {
      type: 'category',
      label: 'Tokens',
      items: [
        'api/tokens/economics',
      ],
    },
  ],

  // guidesSidebar: [

  // ],
};

module.exports = sidebars;
